service: layer-service
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  stage: ${opt:stage, 'dev'}
  endpointType: REGIONAL

layers:
  hello:
    path: myLayer # required, path to layer contents on disk
    name: ${self:service}-${sls:stage}-myLayer # optional, Deployed Lambda layer name
    description: Provides layer level access to the following libraries and their dependencies # optional, Description to publish to AWS
    # compatibleRuntimes: # optional, a list of runtimes this layer is compatible with
    #   - python3.8
    # compatibleArchitectures: # optional, a list of architectures this layer is compatible with
    #   - x86_64
    #   - arm64
    # licenseInfo: GPLv3 # optional, a string specifying license information
    # allowedAccounts: # optional, a list of AWS account IDs allowed to access this layer.
    #   - '*'
    # note: uncommenting this will give all AWS users access to this layer unconditionally.
    retain: true # optional, false by default. If true, layer versions are not deleted as new ones are created
